# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter_cus.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json

class Ui_Form(object):
    def ok_callback(self):
        if self.radioButton_gender.isChecked():
            self.filterbygender()
        if self.radioButton_address.isChecked():
            self.filterbyaddress()
        if self.radioButton_noCriterria.isChecked():
            self.nofilterCriterria()

    def datatotable(self, customer_lỉst):
        key = ['id', "name", "gender", 'phone', "address"]
        self.tableWidget_list.clearContents()
        self.tableWidget_list.setRowCount(len(customer_lỉst))
        for i in range(len(customer_lỉst)):
            st = customer_lỉst[i]
            for j in range(len(key)):
                if j == 6:
                    s = ",".join(st[key[j]]).lower()
                    self.tableWidget_list.setItem(i, j, QtWidgets.QTableWidgetItem(s))

                elif j == 5:
                    if st[key[j]] == False:
                        self.tableWidget_list.setItem(i, j, QtWidgets.QTableWidgetItem("Female"))
                    else:
                        self.tableWidget_list.setItem(i, j, QtWidgets.QTableWidgetItem("Male"))
                else:
                    self.tableWidget_list.setItem(i, j, QtWidgets.QTableWidgetItem(st[key[j]]))
        self.tableWidget_list.resizeColumnsToContents()

    def idExisted(self, id, data):
        for st in data:
            if st['gender'] == id or st['address']== id:
                return st
        return None

    def nofilterCriterria(self):
        data = []
        with open('Customer.json') as f:
            data = json.load(f)
        if data == []:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Information")
            msg.setText("No customer found.")
            msg.exec_()
        else:
            self.datatotable(data)

    def filterbygender(self):
        data = []
        with open('Customer.json') as f:
            data = json.load(f)
        if self.idExisted(self.comboBox_gender.currentText(), data) is None:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Information")
            msg.setText("No customer found")
            msg.exec_()
        else:
            if self.comboBox_gender.currentText() == "Female":
                lst = [st for st in data if st['gender'] == self.comboBox_gender.currentText()]
            if self.comboBox_gender.currentText() == "Male":
                lst = [st for st in data if st['gender'] == self.comboBox_gender.currentText()]
            if self.comboBox_gender.currentText() == "N/A":
                lst = [st for st in data if st['gender'] == self.comboBox_gender.currentText()]
            self.datatotable(lst)

    def filterbyaddress(self):
        data = []
        with open('Customer.json') as f:
            data = json.load(f)
        if self.idExisted(self.comboBox_address2.currentText(), data) is None:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Information")
            msg.setText("No customer found")
            msg.exec_()
        else:
            lst = [st for st in data if st['address'] == self.comboBox_address2.currentText()]
            self.datatotable(lst)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(649, 603)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 601, 571))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_ok = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ok.setGeometry(QtCore.QRect(490, 40, 93, 61))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.tableWidget_list = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_list.setGeometry(QtCore.QRect(20, 160, 551, 391))
        self.tableWidget_list.setRowCount(10)
        self.tableWidget_list.setColumnCount(5)
        self.tableWidget_list.setObjectName("tableWidget_list")
        self.radioButton_address = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_address.setGeometry(QtCore.QRect(20, 80, 200, 25))
        self.radioButton_address.setObjectName("radioButton_address")
        self.radioButton_gender = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_gender.setGeometry(QtCore.QRect(20, 40, 151, 25))
        self.radioButton_gender.setObjectName("radioButton_gender")
        self.comboBox_gender = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_gender.setGeometry(QtCore.QRect(200, 40, 271, 27))
        self.comboBox_gender.setObjectName("comboBox_gender")
        self.radioButton_noCriterria = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_noCriterria.setGeometry(QtCore.QRect(20, 120, 121, 20))
        self.radioButton_noCriterria.setObjectName("radioButton_noCriterria")
        self.comboBox_address2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_address2.setGeometry(QtCore.QRect(200, 80, 271, 27))
        self.comboBox_address2.setObjectName("comboBox_address2")
        # set tableWidlist
        set=['ID customer', "Name","Gender","Phone","Address"]
        self.tableWidget_list.setHorizontalHeaderLabels(set)
        # Gender
        gd = ["Male", "Female", "N/A"]
        self.comboBox_gender.addItems(gd)
        #address
        ad = ["An Giang", "Bac Lieu", "Bac Giang", "Bac Kan", "Bac Ninh", "Ben Tre", "Binh Duong", "Binh Dinh",
              "Binh Phuoc", "Binh Thuan", "Ba Ria - Vung Tau"]
        self.comboBox_address2.addItems(ad)
        # putton Ok
        self.pushButton_ok.clicked.connect(self.ok_callback)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Filter Customer"))
        self.pushButton_ok.setText(_translate("Form", "OK"))
        self.radioButton_address.setText(_translate("Form", "Filter By Address:"))
        self.radioButton_gender.setText(_translate("Form", "Filter By Gender:"))
        self.radioButton_noCriterria.setText(_translate("Form", "No Criterria:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
